repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        args: ['â€”-maxkb=1000']
        name: Check for added large files
      - id: check-ast
        name: Check Python files for parse errors
      - id: check-case-conflict
        name: Check files for case conflicts on case-insensitive filesystems
      - id: check-docstring-first
        name: Check that no code is placed prior to docstrings
      - id: check-executables-have-shebangs
        name: Check that executables have shebangs
      - id: check-illegal-windows-names
        name: Check for illegal Windows filenames
      - id: check-json
        name: Check valid JSON syntax
      - id: check-merge-conflict
        name: Check for files that contain merge conflict strings
      - id: check-shebang-scripts-are-executable
        name: Check that shebang scripts are executable
      - id: check-toml
        name: Check valid TOML syntax
      - id: check-xml
        name: Check valid XML syntax
      - id: check-yaml
        name: Check valid YAML syntax
      - id: end-of-file-fixer
        name: Check for newline at end of file
        exclude: '^LICENSE$'
      - id: debug-statements
        name: Check for debugger imports
      - id: no-commit-to-branch
        name: Check to not commit to main
      - id: trailing-whitespace
        name: Check for trailing whitespaces
  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.0
    hooks:
      - id: bandit
        name: Run bandit (security linter for python)
        args: ["-c", "pyproject.toml", "-r", "-ll", "meshpy/"]
        additional_dependencies: ["bandit[toml]"]
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v19.1.5
    hooks:
      - id: clang-format
        name: Run clang-format (C/C++ formatter)
  - repo: https://github.com/PyCQA/docformatter
    rev: "eb1df347edd128b30cd3368dddc3aa65edcfac38" # change back to version once bug is fixed in latest version to be compatible with pre-commit
    hooks:
      - id: docformatter
        name: Run docformatter (formatter for docstrings)
        args: ["--in-place", "--config=./pyproject.toml", "-r", "meshpy/"]
  - repo: https://github.com/econchick/interrogate
    rev: 1.7.0
    hooks:
      - id: interrogate
        name: Run interrogate (linter for docstrings)
        args: [--fail-under=100, --ignore-init-module, --style=google, -vv]
        exclude: ^website/
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        name: Run mypy (static type checker for python)
        args: ["--install-types", "--non-interactive", "--ignore-missing-imports", "--follow-imports=silent"]
        exclude: ^website/
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: insert-license
        name: Insert license header (//)
        types_or: [c++, c]
        exclude: 'mm$'
        args:
          - --license-filepath
          - LICENSE
          - --comment-style
          - '//'
          - --no-extra-eol
      - id: insert-license
        name: Insert license header (#)
        types_or: [cmake, cython, dockerfile, python, shell]
        args:
          - --license-filepath
          - LICENSE
          - --comment-style
          - '#'
          - --no-extra-eol
  - repo: https://github.com/asmeurer/removestar
    rev: "1.5.2"
    hooks:
      - id: removestar
        name: Run removestar (remove wildcard imports)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.2
    hooks:
      - id: ruff # linter
        name: Run ruff (linter for Python)
        args: ["--fix", "--select", "I"] # "--select I" -> sort imports
      - id: ruff-format # formatter
        name: Run ruff (formatter for Python)
  - repo: https://github.com/crate-ci/typos
    rev: v1.28.4
    hooks:
      - id: typos
        name: Check for typos
        exclude: ".*\\.(nb|wls)$"
  - repo: https://github.com/pamoller/xmlformatter
    rev: v0.2.8
    hooks:
      - id: xml-formatter
        name: Run xml-formatter
        args: [--indent, "2", --indent-char, " ", --selfclose, --overwrite, --eof-newline]
  - repo: https://github.com/google/yamlfmt
    rev: v0.14.0
    hooks:
      - id: yamlfmt
        name: Run yamlfmt
        args: ["-formatter", "retain_line_breaks_single=true"]
